name = "mandelfort"
version = "0.1.0"
license = "license"
author = "Ed Hone"
maintainer = "edwardhone@gmail.com"
copyright = "Copyright 2024, Ed Hone"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
external-modules = ["netcdf"]
link = ["netcdf", "netcdff"]

[library]
include-dir = ["./.spack-env/view/include", "./.spack-env/view/lib"]

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
openmp = "*"